### ISSUE TITLE
Emoji indices are incorrect

### ISSUE THREAD

**Issue by ummjackson** [nojimage/twitter-text-php#12]
Hi there, 

I'm running the current tweet string through the extractor and the indices I'm getting are as follows. 

The username indices are correct, but the URL indices should be 15, 46 instead of 14, 45. It seems like this has to do with the emoji? I know you have StringUtil wrappers which use multi-byte functions, so any ideas how to fix this??

**String:**
`$tweet = "@ummjackson 🤡 https://i.imgur.com/I32CQ81.jpg"`

**Entities**
```json
"entities": {
"user_mentions": [
{
"screen_name": "ummjackson",
"indices": [
0,
11
]
}
],
"hashtags": [],
"urls": [
{
"url": "https://i.imgur.com/I32CQ81.jpg",
"indices": [
14,
45
]
}
]
}
```

**Comment by ummjackson** [comment]
PS. Using the develop branch, but same thing happens on master.

**Comment by ummjackson** [comment]
So it seems that I need the indices in UTF-16 as that's what JS/Java are using... so they're having a hard time mapping the entities back to the body text when emoji are used. Any ideas on how to solve for this @nojimage ?

**Comment by nojimage** [comment]
Emoji is counted as one character.
In this case, it is correct that the index of the URL starts with 14.

**Comment by ummjackson** [comment]
Thanks @nojimage - seems the issue is with how Java/JavaScript count characters as opposed to codepoints. We implemented a fix on that end.
