### ISSUE TITLE
Updating character limit to 280 characters

### ISSUE THREAD

**Issue by nojimage** [nojimage/twitter-text-php#15]
Updating the character limit (and the twitter-text library) - Announcements - Twitter Developers https://twittercommunity.com/t/updating-the-character-limit-and-the-twitter-text-library/96425

twitter-text Parser — Twitter Developers https://developer.twitter.com/en/docs/developer-utilities/twitter-text

**Comment by nojimage** [comment]
I'll wait twitter/twitter-text update 😃

**Comment by victorchat** [comment]
In the meantime, is it possible to extend the class `Validator` and override the constant `MAX_LENGTH`?

**Comment by nojimage** [comment]
Temporarily it will be possible to respond by changing `MAX_LENGTH`. However, counting when CJK characters are included can not be done correctly.

**Comment by victorchat** [comment]
I guess that's as good as it gonna get for me as in right now. I would just delete the child class and use the original one once you apply this feature. Thanks. 😁

**Comment by bwegrzyn** [comment]
Thanks for the hard work, looking forward to this release so I can update my apps. :thumbsup:

**Comment by nihilenz** [comment]
Hi, as you probably know https://github.com/twitter/twitter-text has been updated to 2.0, do you have plans to work on twitter-text-php in the next weeks? Thanks 🙏

**Comment by nojimage** [comment]
I started working on implementing twitter-text 2.0 changes.
However, as I have to do the year-end and new year tasks, The new version will be update at the new year.

**Comment by victorchat** [comment]
Looking forward to the new version 😁

**Comment by nojimage** [comment]
I released twitter-text-php 2.0 now!
Added `Twitter\Text\Parser::parseTweet()` to support extended tweet length.

twitter-text-php 2.0 has some backwards incompatible fixes, such as required `mbstring` and `intl` extensions.

Please see changes in https://github.com/nojimage/twitter-text-php/releases/tag/v2.0.0
