### ISSUE TITLE
Extractor's extract() method is calling other methods with wrong names

### ISSUE THREAD

**Issue by sharelov** [nojimage/twitter-text-php#19]
I updated the package to v 2.0.0 and  when I visit the example page I get this error:

```php
Fatal error: Uncaught Error: Call to undefined method Twitter\Text\Extractor::extractMentionedUsernames() in C:\Users\juaniquillo-laptop-1\Code\sharelov\vendor\nojimage\twitter-text-php\lib\Twitter\Text\Extractor.php:96 Stack trace: #0 C:\Users\juaniquillo-laptop-1\Code\sharelov\vendor\nojimage\twitter-text-php\tests\example.php(124): Twitter\Text\Extractor->extract('Tweet mentionin...') #1 {main} thrown in C:\Users\juaniquillo-laptop-1\Code\sharelov\vendor\nojimage\twitter-text-php\lib\Twitter\Text\Extractor.php on line 96
```
The problem seams to be that some methods are called incorrectly inside the `extract` method. There are 3 of them:

- `extractMentionedUsernames` should be `extractMentionedScreennames`
- `extractRepliedUsernames` should be `extractReplyScreenname` and
- `extractMentionedUsernamesWithIndices` should be `extractMentionedScreennamesWithIndices`

Once I fix those names the example page works as expected.

**Comment by nojimage** [comment]
Oh...I did not notice because the test was not written. Thank you for the report.
