### ISSUE TITLE
Call to undefined function Twitter\Text\idn_to_ascii()

### ISSUE THREAD

**Issue by oguilleux** [nojimage/twitter-text-php#23]
Hi there,

I'm having an issue with the `idn_to_ascii` function. It seems that the server is interpreting the function as a method (that server calls `Twitter\Text\idn_to_ascii()`) and not a native php-intl function. Php 7 + extension intl & mbstring are installed. Here is the error :

Fatal error: Uncaught Error: Call to undefined function Twitter\Text\idn_to_ascii() in /var/www/wordpress/public/wp-content/plugins/twitter/vendor/nojimage/twitter-text-php/lib/Twitter/Text/StringUtils.php:118 Stack trace: 
#0 /var/www/wordpress/public/wp-content/plugins/twitter/vendor/nojimage/twitter-text-php/lib/Twitter/Text/Extractor.php(416): Twitter\Text\StringUtils::idnToAscii(‘t.co’) 
#1 /var/www/wordpress/public/wp-content/plugins/twitter/vendor/nojimage/twitter-text-php/lib/Twitter/Text/Extractor.php(385): Twitter\Text\Extractor->isValidHostAndLength(23, ‘https://’, ‘t.co’) 
#2 /var/www/wordpress/public/wp-content/plugins/twitter/vendor/nojimage/twitter-text-php/lib/Twitter/Text/Extractor.php(114): Twitter\Text\Extractor->extractURLsWithIndices(’https://t.co/1c...') 
#3 /var/www/wordpress/public/wp-content/plugins/twitter/vendor/nojimage/twitter-text-php/lib/Twitter/Text/Autolink.php(493): Twitter\Text\Extractor->extractEntitiesWithIndices(’https://t.c in /var/www/wordpress/public/wp-content/plugins/twitter/vendor/nojimage/twitter-text-php/lib/Twitter/Text/StringUtils.php on line 118

Thanks a lot for your help,

Olivier

**Comment by nojimage** [comment]
It seems intl extension not enabled.
Please check the intl extension loaded in your server. (run `php -m` or call `extension_loaded('intl')` function.

**Comment by oguilleux** [comment]
Solved : the admin forgot to restart Apache. Sorry for the trouble.
