### ISSUE TITLE
Support: problems using this library

### ISSUE THREAD

**Issue by andreasspeck** [nojimage/twitter-text-php#24]
I'm having problems using this library in a Drupal project.

I installed it via composer, and it is being picked up.

However, when I can \Twitter\Text\Parser::parseTweet('Hello World'), I get first a php warning:

Deprecated function: Non-static method Twitter\Text\Parser::parseTweet() should not be called statically in Drupal\social_post_twitter_tweet\Controller\SocialPostTwitterTweetController::validateTweetText()

And then a fatal error:
Error: Using $this when not in object context in Twitter\Text\Parser::parseTweet() (line 68 of /var/www/clients/client1/web201/web/vendor/nojimage/twitter-text-php/lib/Twitter/Text/Parser.php)

Any idea what is wrong? Do I need to initiate the parser in a way?

**Comment by sololance** [comment]
Hi!

You're right, this function can't be called statically. However, you can start new class and use it:

> use Twitter\Text\Parser;
> 
> $parser = new Parser();
> 
> $parser->parseTweet();


I suggest you take a look at examples and better use something like this:

> $data = \Twitter\Text\Extractor::create() ->extract($text);

https://github.com/nojimage/twitter-text-php/blob/master/tests/example.php#L123

I'm will prepare PR for this issue.

Thanks.

**Comment by nojimage** [comment]
it's my document mistake. thank you @sololance :)
