### ISSUE TITLE
"@" symbol should be included in anchor for mentions

### ISSUE THREAD

**Issue by kinglozzer** [nojimage/twitter-text-php#28]
Autolinked `@username` mentions result in a URL like `@<a href="twitter.com/username">username</a>`, when the `@` symbol should be included as part of the anchor

**Comment by sololance** [comment]
Hi!

That's correct, it should be like @<a href="twitter.com/username">username</a>.
 
Official twitter text javascript library result: https://codesandbox.io/s/3849wo8p5

Twitter used to be like https://twitter.com/@jack and later changed it to https://twitter.com/jack

Thanks!

**Comment by sololance** [comment]
> I disagree - if you use the official Twitter iOS/Android app, or browse twitter.com in a web browser, the ‘@‘ is always included in the link

Sure, you can create a new issue here https://github.com/twitter/twitter-text/issues/new

Thanks!

**Comment by sololance** [comment]
Good catch! Probably we can add this feature? What do you think @nojimage ?

**Comment by nojimage** [comment]
Thanks comments. I'll try implements `usernameIncludeSymbol` option.

**Comment by nojimage** [comment]
Hi @kinglozzer, I implemented `setUsernameIncludeSymbol()`.
please try it.

```php
$linker = new Autolink();
$linker->setUsernameIncludeSymbol(true);
$linkedText = $linker->autoLink('@username'); // -> '<a href="twitter.com/username">@username</a>'
```

**Comment by kinglozzer** [comment]
Great, works perfectly. Thanks @nojimage @sololance 😀
