### ISSUE TITLE
Autolink linkToHashtag title attribute just duplicates text value

### ISSUE THREAD

**Issue by jamesmacwhite** [nojimage/twitter-text-php#36]
The AutoLink linkToHashtag function sets the title attribute with the same value of the hash tag text. This is potentially non ideal for accessibility as the title value isn't conveying anything different and is therefore possibly redundant here:

https://github.com/nojimage/twitter-text-php/blob/master/lib/Twitter/Text/Autolink.php#L768

In this case it is identified by WAVE as Redundant title text.

Either the title text should be more informative or advisory or just removed entirely. Removing it entirely is probably easier.

Thoughts?

**Comment by nojimage** [comment]
Thank you for your advice.

However, the format of the generated link is defined by the twitter-text' conformance, and it cannot be changed arbitrarily here.
(see also https://github.com/twitter/twitter-text/blob/master/conformance/autolink.yml

It may be better to post the issue to [twitter-text](https://github.com/twitter/twitter-text).

**Comment by jamesmacwhite** [comment]
@nojimage Thanks. I'll see if I can have this reviewed upstream.
