### ISSUE TITLE
Allow custom URLs

### ISSUE THREAD

**Issue by j3j5** [nojimage/twitter-text-php#44]
Would you be open to a MR to allow customizing the values of the URL base variables? I was thinking of setters like the ones for CSS classes but that would allow the library to output URLs pointing to domains different than twitter.com.

**Comment by nojimage** [comment]
I think that sounds like a good idea. Please submit the merge request, but remember to include appropriate unit tests for your changes.

I look forward to reviewing your proposed changes!

**Comment by j3j5** [comment]
Cool, shall I target `master` or `develop`?

**Comment by nojimage** [comment]
Merged. Thank you for the nice PR.
