### ISSUE TITLE
Exclude carriage return characters

### ISSUE THREAD

**Issue by kochi-luida** [nojimage/twitter-text-php#46]
Sending a tweet containing carriage return characters to the API will not be counted as characters.
To comply with this specification, this library should also exclude carriage return characters from its count.

**Comment by nojimage** [comment]
Thank you for your comment.
Is your point the same as this issue?

[Use of carriage returns in `tweet_length` · Issue #8 · twitter/twitter-text https://github.com/twitter/twitter-text/issues/8](https://github.com/twitter/twitter-text/issues/8#issue-53119697)

**Comment by kochi-luida** [comment]
Yes.
This issue is same with that.

**Comment by nojimage** [comment]
Fixed it. Thanks for reporting 😄
